=== matusbalascak/trezor-suite/packages/firmware-release-config/schema/releases.schema.v1.json
{
    "$id": "https://data.trezor.io/message-releases/schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Releases system",
    "description": "JSON schema of the Trezor firmware releases system.",
    "type": "object",
    "required": ["version", "timestamp", "sequence", "releases", "intermediaries"],
    "properties": {
        "version": {
            "description": "A version of the release message. In case we would change the format of the config itself.",
            "type": "integer",
            "minimum": 1,
            "default": 1
        },
        "timestamp": {
            "$ref": "#/definitions/date-time"
        },
        "sequence": {
            "description": "An increasing counter. Trezor Suite must decline any sequence lower than the latest number. This is to protect against replay attacks, where an attacker could send an older version of the file, and Trezor Suite would accept it.",
            "type": "integer",
            "minimum": 1,
            "default": 1
        },
        "releases": {
            "type": "object",
            "propertyNames": {
                "enum": ["T1B1", "T2B1", "T2T1", "T3B1", "T3T1", "T3W1"]
            },
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "firmware_type": {
                            "type": "string",
                            "enum": ["regular", "bitcoin-only"]
                        },
                        "conditions": {
                            "type": "object",
                            "properties": {
                                "environment": {
                                    "type": "object",
                                    "properties": {
                                        "min_suite_version": {
                                            "type": "string"
                                        }
                                    },
                                    "required": ["min_suite_version"]
                                },
                                "rollout_probability": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 100
                                }
                            },
                            "required": ["environment", "rollout_probability"]
                        },
                        "release": {
                            "type": "object",
                            "properties": {
                                "required": {
                                    "type": "boolean"
                                },
                                "version": {
                                    "type": "array",
                                    "items": {
                                        "type": "integer"
                                    }
                                },
                                "min_bootloader_version": {
                                    "type": "array",
                                    "items": {
                                        "type": "integer"
                                    }
                                },
                                "min_firmware_version": {
                                    "type": "array",
                                    "items": {
                                        "type": "integer"
                                    }
                                },
                                "bootloader_version": {
                                    "type": "array",
                                    "items": {
                                        "type": "integer"
                                    }
                                },
                                "translations": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "firmware_revision": {
                                    "type": "string"
                                },
                                "changelog": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "required",
                                "version",
                                "min_bootloader_version",
                                "min_firmware_version",
                                "bootloader_version",
                                "firmware_revision"
                            ]
                        }
                    },
                    "required": ["firmware_type", "conditions", "release"]
                }
            }
        },
        "intermediaries": {
            "type": "object",
            "propertyNames": {
                "enum": ["T1B1", "T2B1", "T2T1", "T3B1", "T3T1", "T3W1"]
            },
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "min_firmware_version": {
                            "type": "string"
                        },
                        "version": {
                            "type": "integer"
                        }
                    },
                    "required": ["min_firmware_version", "version"]
                }
            }
        }
    },
    "definitions": {
        "date-time": {
            "description": "ISO 8601 date-time format.",
            "type": "string",
            "examples": ["2021-03-03T03:48:16+00:00", "2021-03-03T03:48:16Z"]
        }
    }
}

=== matusbalascak/trezor-suite/packages/firmware-release-config/releases/releases.v1.json
{
    "version": 1,
    "timestamp": "2025-04-25T13:42:57.723Z",
    "sequence": 1,
    "releases": {
        "T1B1": [
            {
                "firmware_type": "regular",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [1, 13, 0],
                    "min_bootloader_version": [1, 12, 0],
                    "min_firmware_version": [1, 12, 0],
                    "bootloader_version": [1, 12, 1],
                    "translations": [],
                    "firmware_revision": "592590cf66a9b62dfeee7e4d2afb6e01005e5b2c",
                    "fingerprint": "253042fb209c78e02482c645b16cc9894c19124e9c9c0c1051b3c68b6e7c700b",
                    "changelog": "* Multisig-related changes.\n* Reworked PIN processing.\n* Fixed the ability to display the XPUB using a QR code."
                }
            },
            {
                "firmware_type": "bitcoin-only",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [1, 13, 0],
                    "min_bootloader_version": [1, 12, 0],
                    "min_firmware_version": [1, 12, 0],
                    "bootloader_version": [1, 12, 1],
                    "translations": [],
                    "firmware_revision": "592590cf66a9b62dfeee7e4d2afb6e01005e5b2c",
                    "fingerprint": "253042fb209c78e02482c645b16cc9894c19124e9c9c0c1051b3c68b6e7c700b",
                    "changelog": "* Multisig-related changes.\n* Reworked PIN processing.\n* Fixed the ability to display the XPUB using a QR code."
                }
            }
        ],
        "T2B1": [
            {
                "firmware_type": "regular",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [2, 8, 9],
                    "min_bootloader_version": [2, 1, 1],
                    "min_firmware_version": [2, 6, 1],
                    "bootloader_version": [2, 1, 8],
                    "translations": ["cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT", "pt-BR"],
                    "firmware_revision": "fad9682201cf9289bba2adb66e6e07ed1cf78936",
                    "fingerprint": "bde9c5ef485548746150e07a9c5081c25f2bdf127707a41f3c487ca83a6c0667",
                    "changelog": "* Ability to cancel recovery on word count selection screen.\n* New UI for confirming long messages."
                }
            },
            {
                "firmware_type": "bitcoin-only",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [2, 8, 9],
                    "min_bootloader_version": [2, 1, 1],
                    "min_firmware_version": [2, 6, 1],
                    "bootloader_version": [2, 1, 8],
                    "translations": ["cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT", "pt-BR"],
                    "firmware_revision": "fad9682201cf9289bba2adb66e6e07ed1cf78936",
                    "fingerprint": "bde9c5ef485548746150e07a9c5081c25f2bdf127707a41f3c487ca83a6c0667",
                    "changelog": "* Ability to cancel recovery on word count selection screen.\n* New UI for confirming long messages."
                }
            }
        ],
        "T2T1": [
            {
                "firmware_type": "regular",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [2, 8, 9],
                    "min_bootloader_version": [2, 0, 0],
                    "min_firmware_version": [2, 0, 8],
                    "bootloader_version": [2, 1, 8],
                    "translations": ["cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT", "pt-BR"],
                    "firmware_revision": "fad9682201cf9289bba2adb66e6e07ed1cf78936",
                    "fingerprint": "e5878fa067df9d1256cdcd86f10869930d85e090c39f807c23f8845472e8d995",
                    "changelog": "* Ability to cancel recovery on word count selection screen.\n* New UI for confirming long messages."
                }
            },
            {
                "firmware_type": "bitcoin-only",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [2, 8, 9],
                    "min_bootloader_version": [2, 0, 0],
                    "min_firmware_version": [2, 0, 8],
                    "bootloader_version": [2, 1, 8],
                    "translations": ["cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT", "pt-BR"],
                    "firmware_revision": "fad9682201cf9289bba2adb66e6e07ed1cf78936",
                    "fingerprint": "e5878fa067df9d1256cdcd86f10869930d85e090c39f807c23f8845472e8d995",
                    "changelog": "* Ability to cancel recovery on word count selection screen.\n* New UI for confirming long messages."
                }
            }
        ],
        "T3B1": [
            {
                "firmware_type": "regular",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [2, 8, 9],
                    "min_bootloader_version": [2, 1, 7],
                    "min_firmware_version": [2, 8, 3],
                    "bootloader_version": [2, 1, 8],
                    "translations": ["cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT", "pt-BR"],
                    "firmware_revision": "fad9682201cf9289bba2adb66e6e07ed1cf78936",
                    "fingerprint": "d3905f15221f7b2733e5496986ceb1a3b39f390c4439e2d3cc89d5f3b7423278",
                    "changelog": "* Ability to cancel recovery on word count selection screen.\n* New UI for confirming long messages."
                }
            },
            {
                "firmware_type": "bitcoin-only",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [2, 8, 9],
                    "min_bootloader_version": [2, 1, 7],
                    "min_firmware_version": [2, 8, 3],
                    "bootloader_version": [2, 1, 8],
                    "translations": ["cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT", "pt-BR"],
                    "firmware_revision": "fad9682201cf9289bba2adb66e6e07ed1cf78936",
                    "fingerprint": "d3905f15221f7b2733e5496986ceb1a3b39f390c4439e2d3cc89d5f3b7423278",
                    "changelog": "* Ability to cancel recovery on word count selection screen.\n* New UI for confirming long messages."
                }
            }
        ],
        "T3T1": [
            {
                "firmware_type": "regular",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [2, 8, 9],
                    "min_bootloader_version": [2, 1, 6],
                    "min_firmware_version": [2, 7, 2],
                    "bootloader_version": [2, 1, 10],
                    "translations": ["cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT", "pt-BR"],
                    "firmware_revision": "fad9682201cf9289bba2adb66e6e07ed1cf78936",
                    "fingerprint": "ac995c394f7a7b3ea4cbd9c04977621d6d2fbef30bba856f707f585f34866ac4",
                    "changelog": "* Ability to cancel recovery flow on word count selection screen.\n* New UI for confirming long messages.\n* Changed \"swipe to continue\" to \"tap to continue\". Screens still respond to swipe-up, but the preferred interaction method is now tapping the lower part of the screen."
                }
            },
            {
                "firmware_type": "bitcoin-only",
                "conditions": {
                    "environment": {
                        "min_suite_version": "25.2.1"
                    },
                    "rollout_probability": 100
                },
                "release": {
                    "required": false,
                    "version": [2, 8, 9],
                    "min_bootloader_version": [2, 1, 6],
                    "min_firmware_version": [2, 7, 2],
                    "bootloader_version": [2, 1, 10],
                    "translations": ["cs-CZ", "de-DE", "es-ES", "fr-FR", "it-IT", "pt-BR"],
